os: osx
language: swift
osx_image: xcode10.2
xcode_scheme: JSSwifter
xcode_project: JSSwifter.xcodeproj
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone 6s

script:
  - xcodebuild clean build test -scheme JSSwifter -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=12.2,name=iPhone 6s'

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    - sibo_jian_29903549@163.com